services:
  postgres:
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=200
    restart: always
    image: "postgres:16-alpine"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
volumes:
  postgres-data:
