packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.59.0
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next
  eslint: ^9.9.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  tailwindcss: ^3.4.10
  typescript: ^5.6
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
